[Desktop Entry]
Type=Application
Name=Správce zástupců
Comment=Spustí utilitu pro správu zástupců ve start menu
Exec=python3 ~/.local/bin/shortcut-manager.py
Icon=system-run
Terminal=false
Categories=Utility;

[Desktop Entry]
Type=Application
Name=Správce zástupců
Comment=Hledání (Win + Mezerník)
Exec=albert toggle
Icon=search
Terminal=false
Categories=System;Utility;