[Desktop Entry]
Type=Application
Name=Správce zástupců
Comment=Spustí utilitu pro správu zástupců ve start menu
Exec=python3 ~/.local/bin/shortcut-manager.py
Icon=system-run
Terminal=false
Categories=Utility;

[Desktop Entry]
Type=Application
Name=Hledat
Comment=Hledání napříč systémem (Win + Mezerník)
Exec=albert toggle
Icon=search
Terminal=false
Categories=System;Utility;

[Desktop Entry]
Type=Application
Name=Wine Windows Program Loader
Exec=wine start /unix %f
MimeType=application/x-ms-dos-executable;application/x-msdownload;application/x-ms-shortcut;
Icon=wine
NoDisplay=true