[General]
additional_path_entires=
showTray=true
telemetry=false
frontend=widgetsboxmodel
hotkey=Meta+Space

[application]
enabled=true

[applications]
enabled=true

[calculator_qalculate]
angle_unit=2
enabled=true

[clipboard]
enabled=true
persistent=true

[docs]
enabled=false

[files]
enabled=true
fs_browsers_show_dirs_first=false

paths=/home/david,/media,/mnt

# Domovská složka
home\david\followSymlinks=true
home\david\indexhidden=false
home\david\maxDepth=100
home\david\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
home\david\nameFilters=@Invalid()
home\david\scanInterval=0
home\david\useFileSystemWatches=true

# Flashky, CD-ROM, a všechno uvnitř /media
media\followSymlinks=true
media\indexhidden=false
media\maxDepth=100
media\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
media\nameFilters=@Invalid()
media\scanInterval=0
media\useFileSystemWatches=true

# Interní pevné disky uvnitř /mnt
mnt\followSymlinks=true
mnt\indexhidden=false
mnt\maxDepth=100
mnt\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
mnt\nameFilters=@Invalid()
mnt\scanInterval=0
mnt\useFileSystemWatches=true

[system]
enabled=false

[widgetsboxmodel]
action_item_padding=6
action_item_selection_border_radius=11
action_item_selection_border_width=0
alwaysOnTop=true
clearOnHide=true
disable_input_method=true
displayScrollbar=true
followCursor=true
hideOnFocusLoss=true
historySearch=true
input_border_radius=11
input_font_size=20
input_padding=5
itemCount=10
result_item_horizontal_spacing=6
result_item_icon_size=39
result_item_padding=6
result_item_selection_border_radius=11
result_item_selection_border_width=0
result_item_subtext_font_size=10
result_item_text_font_size=15
result_item_vertical_spacing=2
showCentered=true
window_border_radius=18
window_border_width=1
window_padding=7
window_shadow_offset=8
window_shadow_size=80
window_spacing=7
window_width=640
