[General]
additional_path_entires=
showTray=false
telemetry=false
frontend=widgetsboxmodel
hotkey=

[application]
enabled=true

[applications]
enabled=true
use_generic_name=true
use_keywords=true
use_non_localized=true

[calculator_qalculate]
angle_unit=2
enabled=true

[clipboard]
enabled=true
persistent=true

[docs]
enabled=false

[files]
enabled=true
fs_browsers_show_dirs_first=false

# 1. Cesty mají normální lomítka (a jsou bez mezer za čárkou)
paths=/home/david,/home/david/.local/share/albert_disks/media,/home/david/.local/share/albert_disks/mnt

# 2. Nastavení pro HOME (Všechna lomítka ZPĚTNÁ, na začátku žádné)
home\david\followSymlinks=true
home\david\indexhidden=false
home\david\maxDepth=100
home\david\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
home\david\nameFilters=@Invalid()
home\david\scanInterval=0
home\david\useFileSystemWatches=true

# 3. Nastavení pro MEDIA portál (Všechna lomítka ZPĚTNÁ, na začátku žádné)
home\david\.local\share\albert_disks\media\followSymlinks=true
home\david\.local\share\albert_disks\media\indexhidden=false
home\david\.local\share\albert_disks\media\maxDepth=100
home\david\.local\share\albert_disks\media\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
home\david\.local\share\albert_disks\media\nameFilters=@Invalid()
home\david\.local\share\albert_disks\media\scanInterval=0
home\david\.local\share\albert_disks\media\useFileSystemWatches=true

# 4. Nastavení pro MNT portál (Všechna lomítka ZPĚTNÁ, na začátku žádné)
home\david\.local\share\albert_disks\mnt\followSymlinks=true
home\david\.local\share\albert_disks\mnt\indexhidden=false
home\david\.local\share\albert_disks\mnt\maxDepth=100
home\david\.local\share\albert_disks\mnt\mimeFilters=inode/directory, application/*, audio/*, font/*, image/*, message/*, model/*, multipart/*, text/*, video/*, application/octet-stream
home\david\.local\share\albert_disks\mnt\nameFilters=@Invalid()
home\david\.local\share\albert_disks\mnt\scanInterval=0
home\david\.local\share\albert_disks\mnt\useFileSystemWatches=true

[system]
enabled=false

[widgetsboxmodel]
action_item_padding=6
action_item_selection_border_radius=11
action_item_selection_border_width=0
alwaysOnTop=true
clearOnHide=true
disable_input_method=true
displayScrollbar=true
followCursor=true
hideOnFocusLoss=true
historySearch=true
input_border_radius=11
input_font_size=20
input_padding=5
itemCount=10
result_item_horizontal_spacing=6
result_item_icon_size=39
result_item_padding=6
result_item_selection_border_radius=11
result_item_selection_border_width=0
result_item_subtext_font_size=10
result_item_text_font_size=15
result_item_vertical_spacing=2
showCentered=true
window_border_radius=18
window_border_width=1
window_padding=7
window_shadow_offset=8
window_shadow_size=80
window_spacing=7
window_width=640
