FILE: tisk.desktop
[Desktop Entry]
Type=Action
Name=Vytisknout...
Icon=printer
Profiles=profile-zero;
[X-Action-Profile profile-zero]
MimeTypes=image/*;application/pdf;text/plain;
Exec=~/.local/bin/print-in-menu %f