# Výchozí textový editor
[featherpad.desktop]
text/plain
text/markdown
text/csv
application/json
application/xml
application/x-shellscript

# Přehrávač videa
[vlc.desktop]
video/mp4
video/x-matroska
video/x-msvideo
video/webm
video/quicktime
video/x-flv

[gdebi.desktop]
application/vnd.debian.binary-package

[wine.desktop]
application/x-ms-dos-executable
application/x-msdownload
application/x-ms-shortcut

[libreoffice-writer.desktop]
application/vnd.openxmlformats-officedocument.wordprocessingml.document

[onlyoffice-desktopeditors.desktop]
application/vnd.openxmlformats-officedocument.wordprocessingml.document