[General]
__userfile__=true
backlightIdleness=50
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=true
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=true
iconType=4
idlenessACAction=-2
idlenessACTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessBatteryAction=-2
idlenessBatteryTime=@Variant(\0\0\0\xf\0\x4\x93\xe0)
idlenessTime=@Variant(\0\0\0\xf\0\0\xea`)
powerLowAction=-1
powerLowLevel=20
powerLowWarning=30
runCheckLevel=1
showIcon=true
