[General]
__userfile__=true

[fancymenu]
alignment=Left
categoriesAtRight=false
icon=/usr/share/lxqt/graphics/helix_60.png
ownIcon=true
customFont=true
customFontSize=15
showText=true
type=fancymenu

[mount]
alignment=Right
type=mount

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=32
lineCount=1
lockPanel=false
opacity=100
panelSize=48
plugins=fancymenu, quicklaunch, taskbar, mount, volume, tray, statusnotifier2, worldclock
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
alignment=Left
type=quicklaunch

[statusnotifier2]
alignment=Left
type=statusnotifier

[taskbar]
alignment=Left
type=taskbar

[tray]
alignment=Right
type=tray

[volume]
alignment=Right
type=volume

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm'</b><br/>'ddd, dd.MM.yyyy'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=false
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=false
timeShowSeconds=false
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=true