[General]
field=0, 5, 7, 38, 32, 42, 44, 45, 51
flags=ExitOnClose, SavePos, infobar, ctrlbar, statbar, cpubar, loadgraph, loadicon, selectpids, hostname, service
font="Sans,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
interval=1300
version=40
viewproc=1

[geometry]
height=517
width=857
x=110
y=88

[sort]
field=44
reversed=false
