# Štítek|Zkratka|Příkaz
Flameshot|Meta+Shift+S|flameshot, gui
Taskmanager|Control+Shift+Escape|qps
CopyQ|Meta+V|copyq-safe.sh, show
BrightnessDown|XF86MonBrightnessDown|brightness.sh, -d
BrightnessUp|XF86MonBrightnessUp|brightness.sh, -i
Terminal|Control+Alt+T|qterminal
Spotlight|Meta+S|albert, toggle
Plocha|Meta+D|toggle-desktop.sh
CtrlAltDeleteMenu|Control+Alt+Delete|cad-menu.py
Lockscreen|Meta+L|dm-tool, lock
FileManager|Meta+E|pcmanfm-qt
Settings|Meta+I|lxqt-config
