# Štítek|Zkratka|Příkaz
Flameshot|Meta+Shift+S|flameshot, gui
Taskmanager|Control+Shift+Escape|qps
CopyQ|Meta+V|copyq, show
BrightnessDown|XF86MonBrightnessDown|brightness.sh, -d
BrightnessUp|XF86MonBrightnessUp|brightness.sh, -i
Terminal|Control+Alt+T|qterminal
Spotlight|Meta+space|albert, toggle
Plocha|Meta+D|toggle-desktop.sh
CtrlAltDeleteMenu|Control+Alt+Delete|cad-menu.py
