xfconf-query -c xfwm4 -p /general/theme -n -t string -s "Default"
xfconf-query -c xfwm4 -p /general/button_layout -n -t string -s "O|HMC"
xfconf-query -c xfwm4 -p /general/title_alignment -n -t string -s "center"
xfconf-query -c xfwm4 -p /general/tile_on_move -n -t bool -s true
xfconf-query -c xfwm4 -p /general/wrap_pointer -n -t bool -s false
xfconf-query -c xfwm4 -p /general/wrap_windows -n -t bool -s false
xfconf-query -c xfwm4 -p /general/snap_to_border -n -t bool -s true
xfconf-query -c xfwm4 -p /general/snap_to_windows -n -t bool -s true