[General]
__userfile__=true
leave_confirmation=false
lock_command=lxqt-logout
window_manager=xfwm4

[Environment]
BROWSER=google-chrome-stable
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
SAL_USE_VCLPLUGIN=qt6
TERM=qterminal

[Touchpad]
SynPS%252F2%2520Synaptics%2520TouchPad\accelSpeed=0.10000000149011612
SynPS%252F2%2520Synaptics%2520TouchPad\naturalScrollingEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\scrollingMethodEnabled=1
SynPS%252F2%2520Synaptics%2520TouchPad\tapToDragEnabled=0
SynPS%252F2%2520Synaptics%2520TouchPad\tappingEnabled=0
TPPS%252F2%2520IBM%2520TrackPoint\accelSpeed=0,1
TPPS%252F2%2520IBM%2520TrackPoint\naturalScrollingEnabled=1
TPPS%252F2%2520IBM%2520TrackPoint\scrollingMethodEnabled=1
TPPS%252F2%2520IBM%2520TrackPoint\tapToDragEnabled=0
TPPS%252F2%2520IBM%2520TrackPoint\tappingEnabled=0
