#!/bin/bash

# Vypnutí interaktivních dotazů
export DEBIAN_FRONTEND=noninteractive

# Konfigurace - true = blokovat jádro, false = povolit
BLOCK_KERNEL=false

# Zmrazení zkompilovaného lxqt panelu
apt-mark hold lxqt-panel > /dev/null 2>&1

# Detekce balíčků jádra (podle architektury)
ARCH=$(dpkg --print-architecture)
if [ "$ARCH" = "amd64" ]; then
    KERNEL_PACKAGES="linux-image-amd64 linux-headers-amd64"
elif [ "$ARCH" = "arm64" ]; then
    KERNEL_PACKAGES="linux-image-arm64 linux-headers-arm64"
else
    KERNEL_PACKAGES="linux-generic"
fi

# Správa zámku jádra
if [ "$BLOCK_KERNEL" = true ]; then
    apt-mark hold $KERNEL_PACKAGES > /dev/null 2>&1
else
    apt-mark unhold $KERNEL_PACKAGES > /dev/null 2>&1
fi

# Samotný update proces
apt-get update -qq
# --force-confold zajistí, že se systém nebude ptát na konfigurační soubory
# a ponechá ty stávající, které jsi v LXQt nebo LightDM ladil.
apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" full-upgrade

# Čištění systému
apt-get autoremove -y -qq
apt-get autoclean -qq